spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/odontologia}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:agenda}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:agenda}
spring.jpa.hibernate.ddl-auto=validate
