spring.application.name=agenda-odontologica
spring.datasource.url=jdbc:mysql://localhost:3306/odontologia
spring.datasource.username=agenda
spring.datasource.password=Desafio969#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false