CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    dni VARCHAR(30) NOT NULL,
    telefono VARCHAR(40) NOT NULL,
    email VARCHAR(254),
    CONSTRAINT uk_patients_dni UNIQUE (dni)
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    patient_id BIGINT NOT NULL,
    motivo VARCHAR(200) NOT NULL,
    notas TEXT,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT fk_appointments_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT ck_appointments_end_after_start CHECK (end_at > start_at),
    CONSTRAINT ck_appointments_status
        CHECK (estado IN ('PROGRAMADO', 'CONFIRMADO', 'CANCELADO', 'ATENDIDO'))
);

CREATE INDEX idx_appointments_start_at ON appointments (start_at);
CREATE INDEX idx_appointments_end_at ON appointments (end_at);
CREATE INDEX idx_appointments_status_start_at ON appointments (estado, start_at);
